### ISSUE TITLE
Several distros need updating to reflect upstream releases or changes

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickemu#456]
- [X]  Alma 8.4 has gone : 8.5, 8.6 and 9.0 are available - #457
- [X] Garuda move to latest is handled in #453
- [X] cachyos - #465 
- [X] freeBSD only 12.4 and 13.0 (and some 13.1 RCs if feeling generous) - #458
- [X] haiku - CDN address not resolving - see https://www.haiku-os.org/get-haiku/r1beta3/ for mirrors - #460
- [X] mxlinux - 21.1 released - #462
- [X] openBSD - 6.8 - 7.1 avail - #459
- [X] fedora is missing 33/i3 and 43/Cinnamon - but best option probably is to just add a note/error message - #461 
- [X] opensuse - 15.4 release - #489
```
OS,Release,Edition,URL
alma,8.4,minimal,http://lon.mirror.rackspace.com/almalinux/8.4/isos/x86_64//AlmaLinux-8.4-x86_64-minimal.iso
alma,8.4,dvd,http://lon.mirror.rackspace.com/almalinux/8.4/isos/x86_64//AlmaLinux-8.4-x86_64-dvd.iso
cachyos,2022.01.09,,https://mirror.cachyos.org/ISO/cachyos-2022.01.09-x86_64.iso
cachyos,2022.02.11,,https://mirror.cachyos.org/ISO/cachyos-2022.02.11-x86_64.iso
fedora,33,i3,
fedora,34,Cinnamon,
freebsd,12.2,disc1,https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/12.2/FreeBSD-12.2-RELEASE-amd64-disc1.iso
freebsd,12.2,dvd1,https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/12.2/FreeBSD-12.2-RELEASE-amd64-dvd1.iso
garuda,220131,dr460nized,http://mirrors.fossho.st/garuda/iso/garuda/dr460nized/220131/garuda-dr460nized-linux-zen-220131.iso
garuda,220131,dr460nized-blackarch,http://mirrors.fossho.st/garuda/iso/garuda/dr460nized-blackarch/220131/garuda-dr460nized-blackarch-linux-zen-220131.iso
garuda,220131,dr460nized-gaming,http://mirrors.fossho.st/garuda/iso/garuda/dr460nized-gaming/220131/garuda-dr460nized-gaming-linux-zen-220131.iso
garuda,220131,bspwm,http://mirrors.fossho.st/garuda/iso/garuda/bspwm/220131/garuda-bspwm-linux-zen-220131.iso
garuda,220131,cinnamon,http://mirrors.fossho.st/garuda/iso/community/cinnamon/220131/garuda-cinnamon-linux-zen-220131.iso
garuda,220131,gnome,http://mirrors.fossho.st/garuda/iso/garuda/gnome/220131/garuda-gnome-linux-zen-220131.iso
garuda,220131,i3,http://mirrors.fossho.st/garuda/iso/garuda/i3/220131/garuda-i3-linux-zen-220131.iso
garuda,220131,kde-barebones,http://mirrors.fossho.st/garuda/iso/garuda/kde-barebones/220131/garuda-kde-barebones-linux-lts-220131.iso
garuda,220131,lxqt-kwin,http://mirrors.fossho.st/garuda/iso/garuda/lxqt-kwin/220131/garuda-lxqt-kwin-linux-zen-220131.iso
garuda,220131,mate,http://mirrors.fossho.st/garuda/iso/community/mate/220131/garuda-mate-linux-zen-220131.iso
garuda,220131,qtile,http://mirrors.fossho.st/garuda/iso/garuda/qtile/220131/garuda-qtile-linux-zen-220131.iso
garuda,220131,sway,http://mirrors.fossho.st/garuda/iso/garuda/sway/220131/garuda-sway-linux-zen-220131.iso
garuda,220131,xfce,http://mirrors.fossho.st/garuda/iso/garuda/xfce/220131/garuda-xfce-linux-lts-220131.iso
haiku,r1beta3,x86_64,https://cdn.haiku-os.org/haiku-release/r1beta3/haiku-r1beta3-x86_64-anyboot.iso
haiku,r1beta3,x86_gcc2h,https://cdn.haiku-os.org/haiku-release/r1beta3/haiku-r1beta3-x86_gcc2h-anyboot.iso
mxlinux,21,Xfce,https://sourceforge.net/projects/mx-linux/files/Final/Xfce/MX-21_x64.iso
mxlinux,21,KDE,https://sourceforge.net/projects/mx-linux/files/Final/KDE/MX-21_KDE_x64.iso
mxlinux,21,Fluxbox,https://sourceforge.net/projects/mx-linux/files/Final/Fluxbox/MX-21_fluxbox_x64.iso
openbsd,6.7,,https://cdn.openbsd.org/pub/OpenBSD/6.7/amd64/install67.iso
```

**Comment by flexiondotorg** [comment]
All of the related pull requests are merged now :smile:
